version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "0.0.0.0:8802:3306"
    environment:
      MYSQL_DATABASE: bms
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: 123
      LANG: C.UTF-8
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:8080:8080"
    working_dir: /bms
    command: ./main
